---
title: Combining orders from Ball and Express for Spring 2024
author: Daniel R. Williams ^[Director of Quality Control, Greenstreet Growers, Lothian,
  MD] ^[PhD Candidate, Dept. of Ag. & Crop Science, Ohio State University, Columbus,  Ohio]
date: 3 April 2023
updated: 24 June 2024
output:
  pdf_document: default
  html_notebook: default
---

# Abstract


```{r setup, echo=FALSE, error=TRUE, message=TRUE, warning=TRUE, include=FALSE}
# this block loads required packages and some custom functions. 

cran_pacs <- c("tidyverse","writexl","fs","stringr","parallel","multidplyr","foreach","doParallel","generics","withr","rlang","janitor","magrittr","purrr","pwalign","readxl","fuzzyjoin","datawizard")
dev_pacs <- c() #"r-dbi/odbc"
bioc_pacs <- c()
py_pacs <- c()

# install installers
if(length(find.package("pak", quiet = TRUE))==0) install.packages("pak")
if(length(find.package("librarian", quiet = TRUE))==0) pak::pak("librarian")
installer_pacs <- Filter(librarian::check_installed, c(if (length(bioc_pacs) > 0) "BiocManager", if (length(py_pacs) > 0) "reticulate"))
if (length(installer_pacs) > 0) pak::pak(installer_pacs, upgrade = TRUE)

# install and load R pacs
r_pacs <- c(cran_pacs,dev_pacs,bioc_pacs) |> unique()
if (length(r_pacs) > 0) {
  pak::pak(r_pacs, upgrade = TRUE)
  librarian::shelf(r_pacs)
}

# install python packs
if (length(py_pacs)>0) {
  if (!reticulate::py_available(initialize = TRUE)) reticulate::install_python()
  if (reticulate::py_available(initialize = TRUE)) reticulate::py_install(py_pacs)
}

## register cores for foreach
n_cores <- parallel::detectCores()
# registerDoParallel(cores=n_cores)
# stopImplicitCluster()

# doParallel cluster
if(!is_null(getDefaultCluster())) stopCluster(getDefaultCluster())
makeCluster(n_cores-1) |> setDefaultCluster()
registerDoParallel(getDefaultCluster())

# dplyr cluster
if(exists("dCluster")) rm(dCluster)
dCluster <- new_cluster(n_cores-1)
cluster_library_quiety <- purrr::quietly(cluster_library)
# cluster_library_quiety(dCluster, loadedNamespaces())
cluster_library_quiety(dCluster, librarian::check_attached())

```

```{r utilityfuns}

## an alignment function for similar names
pairwiseAlightmentMatch = function(x,y) {pwalign::pairwiseAlignment(x,y,scoreOnly = TRUE) > 0}

# name order function. Pulls out words and sorts them. Vectorized.
string_alignment_prep <- function(x) {
  prep_one <- function(y) {
    y |> 
      stringr::str_to_lower() |>
      stringr::str_replace_all("(?<=[:alnum:])[:punct:](?=[:alnum:])"," ") |>
      stringr::str_remove_all("[:punct:]|®|™") |>
      stringr::str_remove_all("(?<=([:space:]|^))(herb)|(he)|(vf)(?=([:space:]|$))") |>
      stringr::str_extract_all("([:alpha:]{2,})|(([:digit:]*(\\.[:digit:]+)?)(?!c$))", simplify = TRUE) |> 
      stringr::str_squish() |> 
      stringr::str_unique() |> 
      as.character() |> 
      stringr::str_sort() |> 
      stringr::str_flatten(collapse = " ")
  }
  sapply(x, prep_one)
}

# this is a two-way name match. Matches are true if the best match x -> y is also the best match y -> x. Vectorized. 
name_match <- function(x,y) {

  x_u <- x |> stringr::str_unique()
  y_u <- y |> stringr::str_unique()
  
  xy_intersect <- generics::intersect(x_u, y_u)
  x_u <- generics::setdiff(x_u,xy_intersect)
  y_u <- generics::setdiff(y_u,xy_intersect)
  
  if((length(x_u) == 0)&(length(y_u) == 0)) {
    out1 <- mapply(\(m,n) {stringr::str_equal(m,n,ignore_case = TRUE)},x,y)
    return(out1)
  }
  
  # print(1)

  doParallel::registerDoParallel(cores=n_cores-1)
  scores <- foreach::foreach(i=1:length(y_u), .combine = rbind, .export = "string_alignment_prep") %dopar% {
    # print("1a")
    raw_score <- pwalign::pairwiseAlignment(x_u |> string_alignment_prep(), y_u[i] |> string_alignment_prep(),scoreOnly = TRUE)
    dplyr::if_else(raw_score>=0,raw_score,-stringr::str_length(paste0(x_u, y_u[i]))/raw_score)
  } |> unlist()
  # print("1b")
  doParallel::stopImplicitCluster()

  # print(2)
  
  y_loc <- apply(scores, 2, which.max) |> unname() |> as.integer()
  x_loc <- apply(scores, 1, which.max) |> unname() |> as.integer()

  x_y_index <- foreach(j=1:length(x_loc), .combine = rbind) %do% c(xname = x_u[x_loc[j]], yname = y_u[j], xi = x_loc[j] |> as.integer(), yi = j |> as.integer())
  y_x_index <- foreach(i=1:length(y_loc), .combine = rbind) %do% c(yname = y_u[y_loc[i]], xname = x_u[i], yi = y_loc[i] |> as.integer(), xi = i |> as.integer())

  # print(3)
  
  joined_index = inner_join(x_y_index |> as_tibble(),y_x_index |> as_tibble()) |>
    mutate(yi = yi |> as.integer(),
           xi = xi |> as.integer(),
           score = scores[yi*xi],
           lmax = pmax(str_length(yname),str_length(xname)),
           lmin = pmin(str_length(yname),str_length(xname)),
           # score_adj = -(lmax)/score,
           score_adj = if_else(score>=0,score,score/(lmax*lmin)))
  
  # TODO ? re-match using the unmatched items from each list. Could also reject matches below a cutoff score.
  
  # print(4)

  out2 <- mapply(\(m,n) {str_equal(m,n,ignore_case = TRUE)|str_equal(joined_index$yname[match(m,joined_index$xname)],n,ignore_case = TRUE)},x,y) |>
    sapply(\(x) {
      if(is.na(x)) FALSE
      else x
      })
  return(out2)
}

# parses file names in a series within a directory to produce an order
order_files <- function(paths, parseFun = identity, baseName = NA) {
  if(length(paths) <= 1) return(paths)
  paths <- paths |> 
    fs::path_file() |>
    fs::path_ext_remove()  
  start <- if(is.na(baseName)) {
    alignment <- pwalign::pairwiseAlignment(paths[2:length(paths)], paths[1])
    alignment@subject@mismatch |> unlist() |> min() 
  } else {
    (baseName |> stringr::str_length()) + 1
  }
  ids <- paths |> stringr::str_sub(start)
  ids |> parseFun() |> 
  base::order()
}

# aligns two strings and returns their matched portion. not working
string_alignment_alike <- Vectorize(function(x,y) {
  # strings <- c(x,y)
  # # strings <- c("Pot 1gal","1g 3pp")
  # sri_order <- strings |> stringr::str_length() |> order(decreasing = TRUE)
  # alignment <- pwalign::pairwiseAlignment(strings[sri_order[1]],strings[sri_order[2]], gapOpening = 10, gapExtension = 4, type = "global")
  # base <- alignment@pattern |> as.character()
  # print(base)
  # print(alignment@pattern@mismatch@unlistData)
  # keepchars <- setdiff(1:str_length(base), alignment@pattern@mismatch@unlistData)
  # print(keepchars)
  # # base |> stringr::str_sub(start = keepchars, end = keepchars) |> stringr::str_flatten() |> stringr::str_squish()
  # strings[sri_order[1]] |> str_sub(start = alignment@pattern@range@start, end = alignment@pattern@range@start + alignment@pattern@range@width -1)
  
  # alignment <- pwalign::pairwiseAlignment(x,y, gapOpening = 10*0, gapExtension = 4*2, type = "global")
  # keepchars <- setdiff(1:str_length(x), alignment@pattern@mismatch@unlistData)
  # # match <- x |> stringr::str_sub(start = keepchars, end = keepchars) |> stringr::str_flatten() |> stringr::str_squish()
  # match <- stringr::str_sub(x, start = alignment@pattern@mismatch@unlistData, end = alignment@pattern@mismatch@unlistData) <- " "
  # match |> stringr::str_flatten() |> stringr::str_squish()
  
  alignment <- pwalign::pairwiseAlignment(x,y, gapOpening = 10*2, gapExtension = 4*1, type = "global")
  match <- alignment@pattern |> as.character() |> str_split_1("")
  keepchars <- setdiff(1:length(match), alignment@pattern@mismatch@unlistData)
  # match[keepchars] |> stringr::str_flatten() |> stringr::str_squish()
  tmp <- character()
  for(i in 1:length(match)) {
    if (i %in% keepchars) tmp[i] <- match[i] else tmp[i] <- " "
  }
  print(tmp)
  tmp |> stringr::str_flatten() |> str_replace_all("[:punct:]"," ") |> stringr::str_squish()
})

# string_alignment_alike(c("plug 288","lin pw 72","Pot 1gal","SD 5K","lin 32lp","32-tray"),c("tray 288","tray 72","point of purchase","pack 5K","tray 32","32 tray"))

```


```{r datasetup, echo=TRUE, error=TRUE, message=FALSE, warning=TRUE, eval=TRUE}
if(is_null(getDefaultCluster())) {
  makeCluster(n_cores-1) |> setDefaultCluster()
  registerDoParallel(getDefaultCluster())
}

plants_dir <- "Greenstreet Growers/TeamSite - Documents/Shared/Production Greenstreet/Production Planning QC/Plant Sales and Orders" |> fs::path_home()
tags_dir <- "Greenstreet Growers/TeamSite - Documents/Shared/Production Greenstreet/Production Planning QC/Tags/" |> fs::path_home()

# e_orders <- plants_dir |> fs::path("Express Seed export","express_open_orders_20240228.xlsx") |>
#   read_xlsx_flex(guess_max = as.integer(.Machine$integer.max/100)) |> 
#   janitor::remove_empty()

# this is a bit excessive, because it really only makes sense to read in the latest open orders file. I've updated to only read the latest open orders file.
e_orders_baseName <- "express_open_orders_"
e_orders_files <- plants_dir |> fs::path("Express Seed export") |> fs::dir_ls() |> fs::path_filter(regex = paste0(e_orders_baseName,".*\\.xlsx"))
e_orders <- foreach::foreach(i=order_files(e_orders_files, baseName = e_orders_baseName, parseFun = ymd) |> max(), .combine = \(x,y) dplyr::rows_upsert(x,y,by = c("Order #", "Purchase Order #", "Customer PO #", "Order Date", "Product #", "Supplier", "QTY Ordered")), .packages = c("readxl")) %dopar% { 
  read_xlsx(e_orders_files[i], guess_max = as.integer(.Machine$integer.max/100)) |>
    janitor::remove_empty("rows") |>
    dplyr::distinct() |>
   dplyr::filter(!is.na(`Order #`))
  } |> janitor::remove_empty()

# e_delivered <- plants_dir |> fs::path("Express Seed export","express_shipped_orders_20240228.xlsx") |>
#   read_xlsx_flex(guess_max = as.integer(.Machine$integer.max/100)) |> 
#   janitor::remove_empty()

e_delivered_baseName <- "express_shipped_orders_"
e_delivered_files <- plants_dir |> fs::path("Express Seed export") |> fs::dir_ls() |> fs::path_filter(regex = paste0(e_delivered_baseName,".*\\.xlsx"))
e_delivered <- foreach::foreach(i=order_files(e_delivered_files, baseName = e_delivered_baseName, parseFun = ymd), .combine = \(x,y) dplyr::rows_upsert(x,y,by = c("Order #", "Purchase Order #", "Customer PO #", "Order Date", "Product #", "Supplier", "QTY Ordered")), .packages = c("readxl")) %dopar% { 
  read_xlsx(e_delivered_files[i], guess_max = as.integer(.Machine$integer.max/100)) |>
    janitor::remove_empty("rows") |>
    dplyr::distinct() |>
   dplyr::filter(!is.na(`Order #`))
  } |> janitor::remove_empty()

# join express delivered and ordered by adding rows from e_orders that do not have a key match in e_delivered
# and pull out sizes
e_combined <- e_orders |>
  filter(`Ship Date` > max(e_delivered$`Ship Date`)) |>
  right_join(e_delivered) |>
  mutate(vendor = "Express",
         Size = Description |> str_squish() |> str_extract("(?<=-)[:alnum:]*$"))

b_baseName <- "order_download_"
b_files <- plants_dir |> fs::path("Ball export") |> fs::dir_ls() |> fs::path_filter(regex = paste0(b_baseName,".*\\.xlsx"))
b_orders <- foreach::foreach(i=order_files(b_files, baseName = b_baseName, parseFun = ymd_hms), .combine = \(x,y) dplyr::rows_upsert(x,y,by = c("Order Number", "Order Line")), .packages = c("readxl","stringr")) %dopar% { 
  read_xlsx(b_files[i], guess_max = as.integer(.Machine$integer.max/100)) |>
    dplyr::mutate(vendor = "Ball",
                 "Order Number" = `Order Number` |> as.character(),
                 "Sales Order Date" = `Sales Order Date` |> lubridate::ymd(),
                 "Ship Date" = `Ship Date` |> lubridate::ymd(),
                 "Total Extended Value" = `Total Extended Value` |> as.numeric(),
                 "Order Line" = `Order Line` |> stringr::str_extract("[:digit:]*"),
                 "Ship Week" = `Ship Week` |> stringr::str_extract("[:digit:]*[:graph:]?[:digit:]*"),
                 "Case Count" = `Case Count` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Unit Price" = `Unit Price` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Royalty" = `Royalty` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Tags" = `Tags` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Freight" = `Freight` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Total Unit Rate" = `Total Unit Rate` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 # "Material Format" = string_alignment_alike(`Size`,`Material Group Description`), ##TODO
                 ) |> 
    dplyr::select(!any_of(c("Not Used1","Not Used2"))) |>
    janitor::remove_empty("rows") |>
    dplyr::distinct() |>
    dplyr::filter(!is.na(`Order Number`))
  } |> janitor::remove_empty() |>
  # unite(col = "Description", any_of(c("Class","Variety")), sep = " ", remove = FALSE)
  rowwise() |>
  mutate("Description" = str_c(`Class`,`Variety`, sep = " "))

mtag_baseName <- "GREENSTREET_GROWERS_INC_Order Export_"
mtag_files <- tags_dir |> fs::path("MasterTag") |> fs::dir_ls() |> fs::path_filter(regex = paste0(mtag_baseName,".*\\.xlsx"))
# registerDoParallel(cores=n_cores-1)
mtag_orders <- foreach::foreach(i=order_files(mtag_files, baseName = mtag_baseName, parseFun = mdy), .combine = \(x,y) dplyr::rows_upsert(x,y,by = c("MT Sales Order #", "MT ID")), .packages = c("foreach")) %dopar% { 
  foreach(j=c(2,1), .combine = dplyr::left_join) %dopar% {
    read_xlsx(path = mtag_files[i], sheet = j, guess_max = as.integer(.Machine$integer.max/100))
  } |> janitor::remove_empty("rows") |>
    dplyr::distinct()
  } |> janitor::remove_empty() |>
    dplyr::mutate(vendor = "MasterTag",
                  "Estimated Ship Date" = `Estimated Ship Date` |> mdy() ) #,
                  # "MT Item Description" = `MT Item Description` |> str_remove_all("[:punct:]|®|™") |> str_squish() |> str_to_lower())


```

```{r singlefileimport, eval=FALSE}

e_orders <- tibble()

e_orders_file <- "Greenstreet Growers/TeamSite - Documents/Shared/Production Greenstreet/Production Planning QC/Plant Sales and Orders/2024/Pansy&Kale 2024" |> fs::path_home() |> fs::path("express_shipped_orders_fall_2023.xlsx")

e_delivered <- read_xlsx_flex(e_orders_file, guess_max = as.integer(.Machine$integer.max/100)) |>
    janitor::remove_empty("rows") |>
    dplyr::distinct() |>
   dplyr::filter(!is.na(`Order #`)) |> 
  janitor::remove_empty()


b_file <- "Greenstreet Growers/TeamSite - Documents/Shared/Production Greenstreet/Production Planning QC/Plant Sales and Orders/2024/Pansy&Kale 2024" |> fs::path_home() |> fs::path("Ball order_download_20240624075842.xlsx")

b_orders <- read_xlsx_flex(b_file, guess_max = as.integer(.Machine$integer.max/100)) |>
    dplyr::mutate(vendor = "Ball",
                 "Order Number" = `Order Number` |> as.character(),
                 "Sales Order Date" = `Sales Order Date` |> lubridate::ymd(),
                 "Ship Date" = `Ship Date` |> lubridate::ymd(),
                 "Total Extended Value" = `Total Extended Value` |> as.numeric(),
                 "Order Line" = `Order Line` |> stringr::str_extract("[:digit:]*"),
                 "Ship Week" = `Ship Week` |> stringr::str_extract("[:digit:]*[:graph:]?[:digit:]*"),
                 "Case Count" = `Case Count` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Unit Price" = `Unit Price` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Royalty" = `Royalty` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Tags" = `Tags` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Freight" = `Freight` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*"),
                 "Total Unit Rate" = `Total Unit Rate` |> stringr::str_extract("[:digit:]*[:punct:]?[:digit:]*")) |> 
    dplyr::select(!any_of(c("Not Used1","Not Used2"))) |>
    janitor::remove_empty("rows") |>
    dplyr::distinct() |>
    dplyr::filter(!is.na(`Order Number`)) |> 
  janitor::remove_empty() |>
  unite(col = "Description", any_of(c("Class","Variety")), sep = " ", remove = FALSE)


## special filters
start_date <- "08-01-2023" |> mdy() |> as.POSIXct() |> as_date() |> is.Date()
end_date <- "10-31-2023" |> mdy()

e_delivered <- e_delivered |>
  mutate(across(where(is.POSIXct),as_date)) |>
  filter(`Ship Date` >= start_date,
         `Ship Date` <= end_date)

b_orders <- b_orders |> 
  mutate(across(where(is.Date),as_date)) |>
  filter(`Ship Date` >= start_date,
         `Ship Date` <= end_date)


```

```{r import_odbc, eval=FALSE}

odbc::odbcListDataSources() |> tail(1) |> select(1) |> unlist()

odbc::odbcListDrivers()

con <- DBI::dbConnect(drv = odbc::odbc(), dsn = odbc::odbcListDataSources() |> tail(1) |> select(1) |> unlist())



```


```{r e_b_join}

# need a function for extracting and alighning the plug tray sizes (etc)
e_combined$Size |> unique()
b_orders$Size |> unique()


alignment <- c("vendor" = "vendor", 
               "Order #" = "Order Number",
               "Customer PO #" = "PO Number", 
               "Order Date" = "Sales Order Date", 
               "Ship Date" = "Ship Date", 
               "Week" = "Ship Week", 
               "Product #" = "Ball Material Number", 
               "Description" = "Description", 
               "Supplier" = "Supplier", 
               "QTY Ordered" = "Quantity", 
               "Total" = "Total Extended Value",
               "Size" = "Size")

b_keep_cols <- alignment |> unname() |> c("Reference Number") |> unique()

plants_joined <- full_join(e_combined, b_orders, by=alignment) |>
  select(names(alignment)) ## |>
  # rowwise() |>
  # mutate(Description = Description |> str_to_lower() |> str_extract_all("([:alpha:]{2,})|([:digit:]*(\\.[:digit:]+)(?!C$))", simplify = TRUE) |> str_squish() |> unique() |> as.character() |> str_flatten(collapse = " "))

```

```{r plant_names_classifications}
# List of herbs with genera and common names
herbs <- list(
  Chamaemelum = c("Chamaemelum","Chamomile","camomile","German chamomile"),
  Matricaria = c("Matricaria","Chamomile","camomile","Roman chamomile"),
  Allium = c("Chive","Garlic","Scallion"),
  Ocimum = c("Ocimum", "Basil", "Holy Basil", "Tulsi"),
  Mentha = c("Mentha", "Mint", "Peppermint", "Spearmint"),
  Petroselinum = c("Petroselinum", "Parsley"),
  Coriandrum = c("Coriandrum", "Cilantro", "Coriander"),
  Salvia = c("Sage", "Salvia-Sage", "garden sage"),
  Thymus = c("Thymus", "Thyme"),
  Rosmarinus = c("Rosmarinus", "Rosemary"),
  Origanum = c("Origanum", "Oregano", "Marjoram"),
  Lavandula = c("Lavandula"),
  Foeniculum = c("Foeniculum", "Fennel"),
  Melissa = c("Melissa", "Lemon balm"),
  Anethum = c("Anethum", "Dill"),
  Cymbopogon = c("Cymbopogon", "Lemongrass"),
  Satureja = c("Satureja", "Savory"),
  Artemisia = c("Tarragon", "Mugwort"),
  Piper = c("Piper", "Black Pepper", "Long Pepper"),
  Zingiber = c("Zingiber", "Ginger"),
  Curcuma = c("Curcuma", "Turmeric"),
  Cinnamomum = c("Cinnamomum", "Cinnamon"),
  Syzygium = c("Syzygium", "Clove"),
  Myristica = c("Myristica", "Nutmeg"),
  Pimenta = c("Pimenta", "Allspice"),
  Capsicum = c("Capsicum", "Chili Pepper", "Paprika", "Cayenne Pepper"),
  Schinus = c("Schinus", "Pink Peppercorn"),
  Elettaria = c("Elettaria", "Cardamom"),
  Apium = c("Apium", "Celery", "Lovage"),
  Nigella = c("Nigella", "Black Cumin", "Nigella"),
  Perilla = c("Perilla", "Shiso"),
  Sesamum = c("Sesamum", "Sesame"),
  Spondias = c("Spondias", "Jocote", "Hog Plum"),
  Trachyspermum = c("Trachyspermum", "Ajwain"),
  Murraya = c("Murraya", "Curry Leaf"),
  Ocotea = c("Ocotea", "Brazilian Nutmeg"),
  Valeriana = c("Valeriana","Valerian"),
  Hyssopus = c("Hyssopus", "Hyssop"),
  Cuminum = c("Cuminum","Cumin"),
  Carum = c("Carum","Caraway"),
  Bergera = c("Bergera","curry leaf", "curry bush", "curry tree","Murraya"),
  Borago = c("Borago","Borage"),
  Hordeum = c("Hordeum vulgare", "barley", "tabby grass", "cat grass"),
  Stevia = c("Stevia","candyleaf", "sweetleaf", "sugarleaf"),
  Eucalyptus = c("Eucalyptus", "red box", "silver dollar", "Baby Blue", "Lemon Bush"),
  Eryngium = c("Eryngium","culantro","cimarrón", "recao", "chardon béni", "Mexican coriander", "samat", "bandhaniya","Burmese coriander", "ngò gai"),
  Helichrysum = c("Helichrysum microphyllum", "Dwarf Curry", "curry dwarf"),
  Anthriscus = c("Anthriscus cerefolium", "Chervil", "French parsley"),
  Ruta = c("Ruta", "Rue"),
  Laurus = c("Laurus nobilis", "bay tree",  "bay laurel", "sweet bay", "true laurel", "Grecian laurel")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "edibles",subdept = "herb", .before = 1)

# List of vegetables with genera and common names
vegetables <- list(
  Brassica = c("Brassica", "Cabbage", "Broccoli", "Cauliflower", "Kale", "Mustard", "Kohlrabi", "Bok Choy", "Pak Choi", "Brussels", "Collards", "Brassica rapa", "turnip"),
  Lactuca = c("Lactuca", "Lettuce", "SimplySalad", "Salad"),
  Spinacia = c("Spinacia", "Spinach"),
  Solanum = c("Solanum", "Tomato", "Eggplant", "Potato", "Tomatillo", "Naranjilla"),
  Cucumis = c("Cucumis", "Cucumber", "Melon", "West Indian Gherkin"),
  Pisum = c("Pisum", "Pea"),
  Phaseolus = c("Phaseolus", "Bean", "Lima Bean", "Mung Bean", "Black Bean"),
  Daucus = c("Daucus", "Carrot"),
  Capsicum = c("Capsicum", "Pepper", "Chili", "Poblano", "Jalapeno"),
  Cucurbita = c("Cucurbita", "^Pumpkin", "Squash", "Zucchini"),
  Apium = c("Apium", "Celery", "Celeriac"),
  Beta = c("Beta", "Beet", "Chard"),
  Rheum = c("Rheum", "Rhubarb"),
  Allium = c("Onion", "Garlic", "Shallot", "Ramp", "Leek"),
  Asparagus = c("Asparagus"),
  Ipomoea = c("Sweet Potato"),
  Raphanus = c("Raphanus", "Radish", "Daikon"),
  Cichorium = c("Cichorium", "Chicory", "Endive", "Radicchio"),
  Amaranthus = c("Amaranthus", "Amaranth"),
  Dioscorea = c("Dioscorea", "Yam"),
  # Colocasia = c("Colocasia", "Taro"),
  Artocarpus = c("Artocarpus", "Breadfruit", "Jackfruit"),
  Abelmoschus = c("Abelmoschus", "Okra"),
  Amorphophallus = c("Amorphophallus", "Konjac"),
  Vigna = c("Vigna", "Cowpea", "Adzuki Bean"),
  Cyphomandra = c("Cyphomandra", "Tamarillo"),
  Lagenaria = c("Lagenaria", "Calabash"),
  Chayote = c("Chayote"),
  Ullucus = c("Ullucus", "Ulluco"),
  Basella = c("Basella", "Malabar Spinach"),
  Eruca = c("Eruca", "Arugula"),
  Moringa = c("Moringa", "Drumstick Tree"),
  Psophocarpus = c("Psophocarpus", "Winged Bean"),
  Pachyrhizus = c("Pachyrhizus", "Jicama"),
  Manihot = c("Manihot", "Cassava"),
  Persea = c("Persea", "Avocado"),
  Portulaca = c("Portulaca oleracea","purslane"),
  Nasturtium = c("Nasturtium", "Watercress","yellowcress"),
  Cynara = c("Cynara", "Artichoke"),
  Physalis = c("Physalis", "groundcherry"),
  Rumex = c("Rumex", "sorrel"), 
  Zea = c("Zea", "SweetCorn", "corn")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "edibles",subdept = "veg", .before = 1)

fruits <- list(
  # Malus = c("Malus", "Apple"),
  # Pyrus = c("Pyrus", "Pear"),
  # Prunus = c("Prunus", "Cherry", "Plum", "Peach", "Nectarine", "Apricot", "Almond"),
  # Rubus = c("Rubus", "Blackberry", "Boysenberry", "Raspberry")
  Fragaria = c("Fragaria", "^Strawberry"), #
  # Vitis = c("Vitis", "Grape"),
  # Citrus = c("Citrus", "Orange", "Lemon", "Lime", "Grapefruit", "Mandarin", "Tangerine"),
  # Musa = c("Musa", "Banana", "Plantain"),
  # Ficus = c("Ficus", "Fig"),
  # Vaccinium = c("Vaccinium", "Blueberry", "Cranberry", "Lingonberry"),
  # Diospyros = c("Diospyros", "Persimmon"),
  # Mangifera = c("Mangifera", "Mango"),
  # Carica = c("Carica", "Papaya"),
  # Annona = c("Annona", "Cherimoya", "Soursop", "Custard Apple"),
  # Passiflora = c("Passiflora", "Passionfruit", "Maracuja"),
  # Actinidia = c("Actinidia", "Kiwi", "Hardy Kiwi"),
  # Carya = c("Carya", "Pecan"),
  # Juglans = c("Juglans", "Walnut"),
  # Pouteria = c("Pouteria", "Sapodilla"),
  # Durio = c("Durio", "Durian"),
  # Syzygium = c("Syzygium", "Rose Apple", "Malay Apple", "Java Apple", "Water Apple"),
  # Litchi = c("Litchi", "Lychee"),
  # Eriobotrya = c("Eriobotrya", "Loquat"),
  # Punica = c("Punica", "Pomegranate"),
  # Tamarindus = c("Tamarindus", "Tamarind"),
  # Morus = c("Morus", "Mulberry"),
  # Garcinia = c("Garcinia", "Mangosteen"),
  # Cydonia = c("Cydonia", "Quince"),
  # Ribes = c("Ribes", "Gooseberry", "Currant"),
  # Ziziphus = c("Ziziphus", "Jujube"),
  # Feijoa = c("Feijoa", "Pineapple Guava"),
  # Spondias = c("Spondias", "Jocote", "Hog Plum"),
  # Elaeagnus = c("Elaeagnus", "Goumi", "Autumn Olive"),
  # Salacca = c("Salacca", "Salak", "Snake Fruit"),
  # Artocarpus = c("Artocarpus", "Jackfruit", "Breadfruit"),
  # Hylocereus = c("Hylocereus", "Dragon Fruit"),
  # Diospyros = c("Diospyros", "Black Sapote", "Chocolate Pudding Fruit"),
  # Persea = c("Persea", "Avocado"),
  # Litchi = c("Litchi", "Lychee"),
  # Nephelium = c("Nephelium", "Rambutan"),
  # Pouteria = c("Pouteria", "Mamey Sapote"),
  # Rollinia = c("Rollinia", "Biriba"),
  # Berberis = c("Berberis", "Barberry"),
  # Mimusops = c("Mimusops", "Mimusops", "Sapodilla"),
  # Tamarillo = c("Cyphomandra", "Tamarillo"),
  Citrullus = c("Citrullus", "^watermelon") #
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "edibles",subdept = "fruit", .before = 1)


## NOW for non-edibles
annuals <- list(
  Tagetes = c("Tagetes", "Marigold"),
  Impatiens = c("Impatiens", "Busy Lizzie", "ImpaEX", "SunpatnsCmp"),
  Petunia = c("Petunia"),
  Pelargonium = c("Pelargonium", "Geranium"),
  Viola = c("Viola", "Pansy", "Panola", "cool[:space:]?wave"),
  Calendula = c( "Calendula", "Pot Marigold"),
  Zinnia = c("Zinnia"),
  Begonia = c("Begonia"),
  Lobelia = c("Lobelia", "Lobelia"),
  Salvia = c("Salvia"),
  Nicotiana = c("Nicotiana", "Flowering Tobacco"),
  Cosmos = c("Cosmos", "Cosmos"),
  Ageratum = c("Ageratum", "Floss Flower"),
  Antirrhinum = c("Antirrhinum", "Snapdragon"),
  Alyssum = c("Alyssum", "Sweet Alyssum"),
  Catharanthus = c("Catharanthus", "Vinca", "Madagascar Periwinkle"),
  Gazania = c("Gazania", "Gazania", "Treasure Flower"),
  Nemesia = c("Nemesia", "Nemesia"),
  Celosia = c("Celosia", "Celosia", "Cockscomb"),
  Dianthus = c("Dianthus", "Dianthus", "Sweet William"),
  Helichrysum = c("Helichrysum", "Strawflower", "Everlasting"),
  Plectranthus = c("Plectranthus", "Coleus"),
  Rudbeckia = c("Rudbeckia", "Black-Eyed Susan"),
  Tropaeolum = c("Tropaeolum", "Nasturtium"),
  Verbena = c("Verbena"),
  Vinca = c("Vinca", "Periwinkle"),
  Lantana = c("Lantana"),
  Phlox = c("Phlox"),
  Tithonia = c("Tithonia", "Mexican Sunflower"),
  Eschscholzia = c("Eschscholzia", "California Poppy"),
  Calibrachoa = c("Calibrachoa", "Million Bells"),
  Gomphrena = c("Gomphrena", "Globe Amaranth"),
  Clarkia = c("Clarkia", "Farewell-to-Spring"),
  Brachyscome = c("Brachyscome", "Swan River Daisy"),
  Torenia = c("Torenia", "Wishbone Flower"),
  Sanvitalia = c("Sanvitalia", "Creeping Zinnia"),
  Osteospermum = c("Osteospermum", "African Daisy"),
  Scaevola = c("Scaevola", "Fan Flower"),
  Nemophila = c("Nemophila", "Baby Blue Eyes"),
  Linaria = c("Linaria", "Toadflax"),
  Gilia = c("Gilia", "Bird's Eye"),
  Clarkia = c("Clarkia", "Godetia"),
  Pennisetum = c("Pennisetum","Ornamental Millet","Millet"),
  Jacobaea = c("Jacobaea", "Dusty Miller", "Senecio cineraria"),
  Centaurea = c("Centaurea", "Centaurea cineraria"),
  Portulaca = c("Portulaca grandiflora","portulaca","rose moss", "eleven o'clock", "moss rose","flor de las once", "bella las once"),
  Melampodium = c("Melampodium"),
  Petchoa = c("Petchoa", "SupCal", "Suprtn", "Suprtna"),
  Dichondra = c("Dichondra", "ponysfoot"),
  Evolvulus = c("Evolvulus"),
  Bacopa = c("Bacopa", "Sutera"),
  Angelonia = c("Angelonia"),
  Cuphea = c("Cuphea"),
  Duranta = c("Duranta"),
  Zizia = c("Zizia"),
  Heliopsis = c("Heliopsis"),
  Pentas = c("Pentas"),
  Cleome = c("Cleome", "spider flower"),
  Alternanthera = c("Alternanthera"),
  Bidens = c("Bidens", "tickseed"),
  Mix = c("MixMaster","TrixiLiner", "Combo", "Mult-sp", "MULTI-PLANT", "MULTI-SPECIES", "Stock ([:alpha:]*[:space:])*Mix"),
  Heliotropium = c("Heliotropium", "Heliotrope"),
  Fuchsia = c("Fuchsia"),
  Erysimum = c("Erysimum", "wallflower"),
  Leucanthemum = c("Leucanthemum", "Shasta Daisy"),
  Oxalis = c("Oxalis"),
  Browallia = c("Browallia"),
  Mecardonia = c("Mecardonia", "axilflower", "Metatera"),
  Strobilanthes = c("Strobilanthes", "persian shield"),
  Iresine = c("Iresine"),
  Ruelia = c("Ruelia"),
  Helianthus = c("Helianthus", "sunflower"),
  Hypoestes = c("Hypoestes", "polka dot plant"),
  Lobularia = c("Lobularia"),
  Gerbera = c("Gerbera"),
  Arctotis = c("Arctotis", "Gousblom", "African daisy"),
  Abutilon = c("Abutilon"),
  Dorotheanthus = c("Dorotheanthus"),
  Streptocarpella = c("Streptocarpella"),
  Colocasia = c("Colocasia"),
  Crossandra = c("Crossandra"),
  Lysimachia = c("Lysimachia"),
  Ipomoea = c("Ipomoea")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "annuals", subdept = "annuals", .before = 1)

perennials <- list(
  Hemerocallis = c("Hemerocallis", "Daylily"),
  Echinacea = c("Echinacea", "Coneflower"),
  Rudbeckia = c("Rudbeckia", "Black-Eyed Susan"),
  Hosta = c("Hosta", "Plantain Lily"),
  Lavandula = c("Lavandula", "Lavender"),
  Phlox = c("Phlox", "Phlox"),
  Sedum = c("Sedum", "Stonecrop"),
  Achillea = c("Achillea", "Yarrow"),
  Astilbe = c("Astilbe", "Astilbe", "False Goat's Beard"),
  Geranium = c("Geranium", "Cranesbill"),
  Heuchera = c("Heuchera", "Coral Bells"),
  Alchemilla = c("Alchemilla", "Lady's Mantle"),
  Nepeta = c("Nepeta", "Catmint"),
  Coreopsis = c("Coreopsis", "Tickseed"),
  Dianthus = c("Dianthus", "Pinks", "Carnation"),
  Delphinium = c("Delphinium", "Larkspur"),
  Iris = c("Iris"),
  Monarda = c("Monarda", "Bee Balm"),
  Peony = c("Peony"),
  Digitalis = c("Digitalis", "Foxglove"),
  Aquilegia = c("Aquilegia", "Columbine"),
  Gaillardia = c("Gaillardia", "Blanket Flower"),
  Liatris = c("Liatris", "Blazing Star", "Gayfeather"),
  Veronica = c("Veronica", "Speedwell"),
  Penstemon = c("Penstemon", "Beardtongue"),
  Baptisia = c("Baptisia", "False Indigo"),
  Lupinus = c("Lupinus", "Lupine"),
  Artemisia = c("Artemisia", "Wormwood"),
  Campanula = c("Campanula", "Bellflower"),
  Helleborus = c("Helleborus", "Hellebore"),
  Kniphofia = c("Kniphofia", "Red Hot Poker"),
  Papaver = c("Papaver", "Poppy"),
  Stachys = c("Stachys", "Lamb'?s Ear"),
  Dicentra = c("Dicentra", "Bleeding Heart"),
  Platycodon = c("Platycodon", "Balloon Flower"),
  Bergenia = c("Bergenia", "Pigsqueak"),
  Pulmonaria = c("Pulmonaria", "Lungwort"),
  Gaura = c("Gaura", "Beeblossom"),
  Brunnera = c("Brunnera", "Siberian Bugloss"),
  Ajuga = c("Ajuga", "Bugleweed"),
  Eryngium = c("Eryngium", "Sea Holly"),
  Armeria = c("Armeria", "Sea Thrift"),
  Ligularia = c("Ligularia", "Leopard Plant"),
  Tiarella = c("Tiarella", "Foamflower"),
  Chrysanthemum = c("Chrysanthemum", "Garden Mum"),
  Agapanthus = c("Agapanthus", "Lily of the Nile"),
  Aruncus = c("Aruncus", "Goat'?s Beard"),
  Verbascum = c("Verbascum", "Mullein"),
  Lychnis = c("Lychnis", "Campion"),
  Perovskia = c("Perovskia", "Russian Sage"),
  Oenothera = c("Oenothera", "Evening Primrose"),
  Phlomis = c("Phlomis", "Jerusalem Sage"),
  Dicliptera = c("Dicliptera", "Hummingbird Plant"),
  Anemone = c("Anemone", "Windflower"),
  Echinops = c("Echinops", "Globe Thistle"),
  Rudbeckia = c("Rudbeckia", "Black-?Eyed Susan"),
  Kniphofia = c("Kniphofia", "Red Hot Poker"),
  Thalictrum = c("Thalictrum", "Meadow Rue"),
  Antennaria = c("Antennaria", "pussytoes"),
  Sagina = c("Sagina"),
  Buddleja = c("Buddleja","Buddleia","butterfly bush"),
  Asclepias = c("Asclepias", " butterfly weed", "milkweed"),
  Agastache = c("Agastache", "giant hyssop", "hummingbird mint"),
  Chelone = c("Chelone", "turtlehead"),
  Helenium = c("Helenium", "sneezeweed"),
  Eucomis = c("Eucomis", "pineapple flower", "pineapple lily"),
  Stokesia = c("Stokesia"),
  Amsonia = c("Amsonia", "bluestar", "blue star"),
  Vernonia = c("Vernonia", "ironweed", "hawkweed"),
  Argyranthemum = c("Argyranthemum"),
  Calylophus = c("Calylophus", "sundrop"),
  Felicia = c("Felicia"),
  Euryops = c("Euryops", "busy daisy"),
  Ballota = c("Ballota", "Horehound"),
  Chrysogonum = c("Chrysogonum"),
  Polemonium = c("Polemonium"),
  Epimedium = c("Epimedium"),
  Lamium = c("Lamium", "lamiastrum", "Dead-?nettle"),
  Delosperma = c("Delosperma", "ice plant"),
  Meehania = c("Meehania"),
  Physostegia = c("Physostegia", "obedient plant", "lionsheart", "false dragonhead"),
  Solidago = c("Solidago", "Goldenrod", "golden rod"),
  Geum = c("Geum", "avens"),
  Gillenia = c("Gillenia"),
  Sidalcea = c("Sidalcea"),
  Tricyrtis = c("Tricyrtis"),
  Belamcanda = c("Belamcanda"),
  Heucherella = c("Heucherella"),
  Ophiopogon = c("Ophiopogon"),
  Lewisia = c("Lewisia"),
  Scabiosa = c("Scabiosa"),
  Ceratostigma = c("Ceratostigma", "hardy plumbago"),
  Arenaria = c("Arenaria", "sandwort"),
  Helianthus = c("Helianthus tuberosus", "Jerusalem artichoke", "sunchoke"),
  Polygonatum = c("Polygonatum", "Solomon's seal"),
  Hypericum = c("Hypericum"),
  Eupatorium = c("Eupatorium"),
  Lithodora = c("Lithodora"),
  Liriope = c("Liriope"),
  Mangave = c("Mangave"),
  Calamintha = c("Calamintha"),
  Corydalis = ("Corydalis"),
  Veronicastrum = c("Veronicastrum"),
  Digiplexis = c("Digiplexis"),
  Ratibida = c("Ratibida"),
  Acanthus = c("Acanthus"),
  Cimicifuga = c("Cimicifuga"),
  Aralia = c("Aralia cordata", "Sun King"),
  Erigeron = c("Erigeron"),
  Spigelia = c("Spigelia"),
  Nipponanthemum = c("Nipponanthemum"),
  Sisyrinchium = c("Sisyrinchium"),
  Acanthus = c("Acanthus"),
  Nierembergia = c("Nierembergia", "cupflower"),
  Fatsia = c("Fatsia"),
  Tolmiea = c("Tolmiea"),
  Plumbago = c("Plumbago"),
  Isotoma = c("Isotoma"),
  Artemisia = c("Artemisia", "Wormwood"),
  Aster = ("aster")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "perennials", subdept = "perennials", .before = 1)

succulents <- list(
  Aloe = c("Aloe"),
  Agave = c("Agave"),
  Echeveria = c("Echeveria"),
  Crassula = c("Crassula", "Jade Plant"),
  Sedum = c("Sedum", "Stonecrop"),
  Kalanchoe = c("Kalanchoe"),
  Haworthia = c("Haworthia"),
  Sempervivum = c("Sempervivum", "Hens and Chicks"),
  Euphorbia = c("Euphorbia", "Spurge"),
  Gasteria = c("Gasteria", "Gasteria"),
  Pachyphytum = c("Pachyphytum", "Pachyphytum"),
  Graptopetalum = c("Graptopetalum", "Ghost Plant"),
  Aeonium = c("Aeonium", "Aeonium"),
  Adromischus = c("Adromischus", "Adromischus"),
  Cotyledon = c("Cotyledon", "Cotyledon"),
  Dudleya = c("Dudleya", "Dudleya"),
  Sansevieria = c("Sansevieria", "Snake Plant"),
  Lithops = c("Lithops", "Living Stone"),
  Senecio = c("Senecio", "String of Pearls", "Blue Chalksticks"),
  Portulacaria = c("Portulacaria", "Elephant Bush"),
  Rhipsalis = c("Rhipsalis", "Mistletoe Cactus"),
  Schlumbergera = c("Schlumbergera", "Christmas Cactus"),
  Opuntia = c("Opuntia", "Prickly Pear"),
  Mammillaria = c("Mammillaria", "Pincushion Cactus"),
  Ferocactus = c("Ferocactus", "Barrel Cactus"),
  Echinocactus = c("Echinocactus", "Golden Barrel Cactus"),
  Gymnocalycium = c("Gymnocalycium", "Chin Cactus"),
  Astrophytum = c("Astrophytum", "Bishop'?s Cap Cactus"),
  Cereus = c("Cereus", "Peruvian Apple Cactus"),
  Parodia = c("Parodia", "Ball Cactus"),
  Stenocactus = c("Stenocactus", "Brain Cactus"),
  Echinopsis = c("Echinopsis", "Hedgehog Cactus"),
  Rebutia = c("Rebutia", "Crown Cactus"),
  Notocactus = c("Notocactus", "Balloon Cactus"),
  Melocactus = c("Melocactus", "Turk's Cap Cactus"),
  Acanthocereus = c("Acanthocereus", "Triangle Cactus"),
  Myrtillocactus = c("Myrtillocactus", "Blue Myrtle Cactus"),
  Cleistocactus = c("Cleistocactus", "Silver Torch Cactus"),
  Pachycereus = c("Pachycereus", "Cardon"),
  Epiphyllum = c("Epiphyllum", "Orchid Cactus"),
  Hylocereus = c("Hylocereus", "Dragon Fruit Cactus"),
  Disocactus = c("Disocactus", "Rat-Tail Cactus"),
  Aporocactus = c("Aporocactus", "Rat's Tail Cactus"),
  Austrocylindropuntia = c("Austrocylindropuntia", "Eve's Needle Cactus"),
  Eulychnia = c("Eulychnia", "Old Man Cactus"),
  Matucana = c("Matucana"),
  Neobuxbaumia = c("Neobuxbaumia", "Giant Mexican Cactus"),
  Espostoa = c("Espostoa", "Peruvian Old Man Cactus"),
  Ariocarpus = c("Ariocarpus", "Living Rock Cactus"),
  Turbinicarpus = c("Turbinicarpus"),
  Coryphantha = c("Coryphantha", "Beehive Cactus"),
  Pilosocereus = c("Pilosocereus", "Blue Torch Cactus"),
  Selenicereus = c("Selenicereus", "Moonlight Cactus"),
  Leuchtenbergia = c("Leuchtenbergia", "Agave Cactus")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "house", subdept = "succ", .before = 1)

foliage <- list(
  Monstera = c("Monstera", "Swiss Cheese Plant"),
  Ficus = c("Ficus", "Fiddle Leaf Fig", "FLF", "Rubber Plant"),
  Philodendron = c("Philodendron"),
  Epipremnum = c("Epipremnum", "Pothos"),
  Spathiphyllum = c("Spathiphyllum", "Peace Lily"),
  Dracaena = c("Dracaena", "Dragon Tree", "Song of India"),
  Calathea = c("Calathea", "Prayer Plant"),
  Maranta = c("Maranta"),
  Dieffenbachia = c("Dieffenbachia", "Dumb Cane"),
  Schefflera = c("Schefflera", "Umbrella Plant"),
  Alocasia = c("Alocasia"),
  Zamioculcas = c("Zamioculcas", "ZZ Plant"),
  Chlorophytum = c("Chlorophytum", "Spider Plant"),
  Asplenium = c("Asplenium", "Bird('?s)? Nest Fern"),
  Nephrolepis = c("Nephrolepis", "Boston Fern"),
  Pteris = c("Pteris", "Brake Fern"),
  Aglaonema = c("Aglaonema"),
  Aspidistra = c("Aspidistra", "Cast Iron Plant"),
  Codiaeum = c("Codiaeum", "Croton"),
  Anthurium = c("Anthurium"),
  Chamaedorea = c("Chamaedorea", "Parlor Palm"),
  Adiantum = c("Adiantum", "Maidenhair Fern"),
  Peperomia = c("Peperomia", "Radiator Plant"),
  Acalypha = c("Acalypha", "Copperleaf"),
  Fittonia = c("Fittonia", "Nerve Plant"),
  Pilea = c("Pilea", "Chinese Money Plant", "Pilea"),
  Cordyline = c("Cordyline", "Ti Plant"),
  Beaucarnea = c("Beaucarnea", "Ponytail Palm"),
  Caladium = c("Caladium"),
  Stromanthe = c("Stromanthe", "Tricolor Ginger"),
  Musa = c("Musa", "Banana"),
  Tradescantia = c("Tradescantia"),
  Araucaria = c("Araucaria", "Norfolk Island Pine"),
  Hedera = c("Hedera", "English Ivy"),
  Syngonium = c("Syngonium", "Nephthytis", "Arrowhead Vine", "Arrowhead Plant"),
  Rhapis = c("Rhapis", "Lady Palm"),
  Ctenanthe = c("Ctenanthe"),
  Rhoeo = c("Rhoeo"),
  Caryota = c("Caryota", "Fishtail Palm"),
  Rhaphidophora = c("Rhaphidophora", "Mini Monstera"),
  Begonia = c("Begonia"),
  Calocephalus = c("Calocephalus", "Silver Bush"),
  Pandanus = c("Pandanus", "Screw Pine"),
  Soleirolia = c("Soleirolia", "Baby's Tears"),
  Neoregelia = c("Neoregelia"),
  Guzmania = c("Guzmania"),
  Vriesea = c("Vriesea"),
  Tillandsia = c("Tillandsia", "Air Plant"),
  Yucca = c("Yucca"),
  Alpinia = c("Alpinia", "Variegated Ginger"),
  Strelitzia = c("Strelitzia", "Bird of Paradise"),
  Phoenix = c("Phoenix", "Pygmy Date Palm"),
  Schefflera = c("Schefflera", "Umbrella Tree"),
  Polyscias = c("Polyscias", "Ming Aralia"),
  Radermachera = c("Radermachera", "China Doll Plant"),
  Clivia = c("Clivia"),
  Aechmea = c("Aechmea", "Urn Plant"),
  Aralia = c("Aralia")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "house", subdept = "foliage", .before = 1)

bulbs_tubers <- list(
  Tulipa = c("Tulipa", "Tulip"),
  Narcissus = c("Narcissus", "Daffodil"),
  Crocus = c("Crocus"),
  Dahlia = c("Dahlia"),
  Gladiolus = c("Gladiolus", "Gladiolus"),
  Lilium = c("Lilium", "Lily"),
  Hyacinthus = c("Hyacinthus", "Hyacinth"),
  Iris = c("Iris"),
  Allium = c("Allium", "Ornamental Onion"),
  Muscari = c("Muscari", "Grape Hyacinth"),
  Colchicum = c("Colchicum", "Autumn Crocus"),
  Anemone = c("Anemone", "Windflower"),
  Fritillaria = c("Fritillaria", "Fritillary"),
  Scilla = c("Scilla", "Squill"),
  Erythronium = c("Erythronium"),
  Ranunculus = c("Ranunculus", "Buttercup"),
  Zantedeschia = c("Zantedeschia", "Calla Lily"),
  Lycoris = c("Lycoris", "Spider Lily"),
  Galanthus = c("Galanthus", "Snowdrop"),
  Leucojum = c("Leucojum", "Snowflake"),
  Crocosmia = c("Crocosmia", "Montbretia"),
  Canna = c("Canna", "Canna Lily"),
  Alstroemeria = c("Alstroemeria", "Peruvian Lily"),
  Tigridia = c("Tigridia", "Tiger Flower")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "perennials", subdept = "bulbs_tubers", .before = 1)

ornamental_grasses <- list(
  Miscanthus = c("Miscanthus", "Maiden Grass"),
  Pennisetum = c("Pennisetum", "Fountain Grass"),
  Festuca = c("Festuca", "Blue Fescue"),
  Stipa = c("Stipa", "Feather Grass"),
  Panicum = c("Panicum", "Switchgrass"),
  Calamagrostis = c("Calamagrostis", "Feather Reed Grass"),
  Helictotrichon = c("Helictotrichon", "Blue Oat Grass"),
  Cortaderia = c("Cortaderia", "Pampas Grass"),
  Carex = c("Carex", "Sedge"),
  Hakonechloa = c("Hakonechloa", "Japanese Forest Grass"),
  Molinia = c("Molinia", "Moor Grass"),
  Schizachyrium = c("Schizachyrium", "Little Bluestem"),
  Chasmanthium = c("Chasmanthium", "Northern Sea Oats"),
  Imperata = c("Imperata", "Japanese Blood Grass"),
  Sporobolus = c("Sporobolus", "Prairie Dropseed"),
  Andropogon = c("Andropogon", "Big Bluestem"),
  Arundo = c("Arundo", "Giant Reed"),
  Eragrostis = c("Eragrostis", "Lovegrass"),
  Muhlenbergia = c("Muhlenbergia", "Muhly Grass"),
  Grass = c("grass")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "perennials", subdept = "grass", .before = 1)

aquatic_plants <- list(
  Nymphaea = c("Nymphaea", "Water Lily"),
  Eichhornia = c("Eichhornia", "Water Hyacinth"),
  Nelumbo = c("Nelumbo", "Lotus"),
  Typha = c("Typha", "Cattail"),
  Pontederia = c("Pontederia", "Pickerelweed"),
  Iris = c("Water Iris"),
  Cyperus = c("Cyperus", "Papyrus"),
  Alisma = c("Alisma", "Water Plantain"),
  Myriophyllum = c("Myriophyllum", "Water Milfoil"),
  Sagittaria = c("Sagittaria"),
  Hydrocotyle = c("Hydrocotyle", "Pennywort"),
  Pistia = c("Pistia", "Water Lettuce"),
  Aponogeton = c("Aponogeton"),
  Lobelia = c("Lobelia", "Cardinal Flower"),
  Thalia = c("Thalia", "Powdery Thalia"),
  Acorus = c("Acorus", "Sweet Flag")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "aquatic", subdept = "aquatic", .before = 1)

trees_shrubs <- list(
  Acer = c("Acer", "Maple"),
  Quercus = c("Quercus", "Oak"),
  Rhododendron = c("Rhododendron"),
  Hydrangea = c("Hydrangea"),
  Camellia = c("Camellia"),
  Cornus = c("Cornus", "Dogwood"),
  Magnolia = c("Magnolia"),
  Ilex = c("Ilex", "Holly"),
  Prunus = c("Prunus", "^Cherry", "^Plum"),
  Buxus = c("Buxus", "Boxwood"),
  Juniperus = c("Juniperus", "Juniper"),
  Viburnum = c("Viburnum"),
  Berberis = c("Berberis", "Barberry"),
  Forsythia = c("Forsythia", "Forsythia"),
  Taxus = c("Taxus", "Yew"),
  Cotoneaster = c("Cotoneaster", "Cotoneaster"),
  Ligustrum = c("Ligustrum", "Privet"),
  Philadelphus = c("Philadelphus", "Mock Orange"),
  Chaenomeles = c("Chaenomeles", "Flowering Quince"),
  Euonymus = c("Euonymus", "Spindle Tree"),
  Cercis = c("Cercis", "Redbud"),
  Amelanchier = c("Amelanchier", "Serviceberry"),
  Hamamelis = c("Hamamelis", "Witch Hazel"),
  Wisteria = c("Wisteria"),
  Carpinus = c("Carpinus", "Hornbeam"),
  Fagus = c("Fagus", "Beech"),
  Salix = c("Salix", "Willow"),
  Liriodendron = c("Liriodendron", "Tulip Tree"),
  Malus = c("Malus", "Crabapple"),
  Rosa = c("Rosa", "^Rose"),
  Caryopteris = c("Caryopteris"),
  Hibiscus = c("Hibiscus"),
  Lagerstroemia = c("Lagerstroemia", "crepe myrtle")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "woody", subdept = "trees", .before = 1)

climbers_vines <- list(
  Clematis = c("Clematis"),
  Wisteria = c("Wisteria"),
  Lonicera = c("Lonicera", "Honeysuckle"),
  Passiflora = c("Passiflora", "^Passionflower"),
  Parthenocissus = c("Parthenocissus", "Virginia Creeper"),
  Hedera = c("Hedera", "^Ivy", "English Ivy"),
  Jasminum = c("Jasminum"),
  Campsis = c("Campsis", "Trumpet Vine"),
  Bougainvillea = c("Bougainvillea"),
  Akebia = c("Akebia", "Chocolate Vine"),
  Trachelospermum = c("Trachelospermum", "Star Jasmine"),
  Thunbergia = c("Thunbergia"),
  Bignonia = c("Bignonia", "Crossvine"),
  Aristolochia = c("Aristolochia", "Dutchman's Pipe"),
  Vitis = c("Vitis", "^Grape"),
  Clitoria = c("Clitoria", "Butterfly Pea"),
  Dioscorea = c("Dioscorea", "Air Potato"),
  Mandevilla = c("Mandevilla", "Dipladenia")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "woody", subdept = "vines", .before = 1)

orchids <- list(
  Phalaenopsis = c("Phalaenopsis", "Moth Orchid"),
  Cattleya = c("Cattleya", "Cattleya Orchid"),
  Dendrobium = c("Dendrobium", "Dendrobium Orchid"),
  Oncidium = c("Oncidium", "Dancing Lady Orchid"),
  Paphiopedilum = c("Paphiopedilum", "Lady's Slipper Orchid"),
  Vanda = c("Vanda", "Vanda Orchid"),
  Cymbidium = c("Cymbidium", "Boat Orchid"),
  Miltonia = c("Miltonia", "Pansy Orchid"),
  Ludisia = c("Ludisia", "Jewel Orchid"),
  Epidendrum = c("Epidendrum", "Crucifix Orchid"),
  Zygopetalum = c("Zygopetalum", "Zygopetalum Orchid"),
  Brassavola = c("Brassavola", "Lady of the Night Orchid"),
  Masdevallia = c("Masdevallia", "Masdevallia Orchid"),
  Laelia = c("Laelia", "Laelia Orchid"),
  Angraecum = c("Angraecum", "Comet Orchid"),
  Catasetum = c("Catasetum", "Catasetum Orchid"),
  Coelogyne = c("Coelogyne", "Necklace Orchid"),
  Phragmipedium = c("Phragmipedium", "Phragmipedium Orchid"),
  Grammatophyllum = c("Grammatophyllum", "Tiger Orchid"),
  Lycaste = c("Lycaste", "Lycaste Orchid")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "house", subdept = "orchid", .before = 1)

groundcovers <- list(
  Pachysandra = c("Pachysandra", "Japanese Spurge"),
  Ajuga = c("Ajuga", "Bugleweed"),
  Vinca_minor = c("Vinca_minor", "Periwinkle"),
  # Sedum = c("Sedum", "Stonecrop"),
  Lamium = c("Lamium", "Dead Nettle"),
  Cerastium = c("Cerastium", "Snow-in-Summer"),
  Thymus = c("Thymus", "Creeping Thyme"),
  Arctostaphylos = c("Arctostaphylos", "Bearberry"),
  Galium = c("Galium", "Sweet Woodruff"),
  Tiarella = c("Tiarella", "Foamflower"),
  Phlox_subulata = c("Phlox subulata", "Creeping Phlox"),
  # Lysimachia = c("Lysimachia", "Creeping Jenny"),
  # Hosta = c("Hosta", "Plantain Lily"),
  # Heuchera = c("Heuchera", "Coral Bell"),
  Waldsteinia = c("Waldsteinia"),
  Veronica = c("Veronica", "Creeping Speedwell"),
  Iberis = c("Iberis", "Candytuft"),
  # Muehlenbeckia = c("Muehlenbeckia", "Creeping Wire Vine"),
  Mazus = c("Mazus")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "annuals", subdept = "groundcover", .before = 1)

bamboo <- list(
  Phyllostachys = c("Phyllostachys", "Running Bamboo"),
  Bambusa = c("Bambusa"),
  Fargesia = c("Fargesia"),
  Pleioblastus = c("Pleioblastus", "Dwarf Bamboo"),
  Sasa = c("Sasa", "Sasa Bamboo"),
  Chimonobambusa = c("Chimonobambusa", "Square Bamboo"),
  Semiarundinaria = c("Semiarundinaria", "Japanese Bamboo"),
  Indocalamus = c("Indocalamus", "Giant Leaf Bamboo"),
  Shibataea = c("Shibataea", "Ruscus Leaf Bamboo"),
  Dendrocalamus = c("Dendrocalamus", "Giant Bamboo"),
  Thamnocalamus = c("Thamnocalamus", "Mountain Bamboo"),
  Yushania = c("Yushania", "African Bamboo")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "woody", subdept = "bamboo", .before = 1)

palms_cycads <- list(
  Chamaedorea = c("Chamaedorea", "Parlor Palm"),
  Cycas = c("Cycas", "Sago Palm"),
  Phoenix = c("Phoenix", "Date Palm"),
  Washingtonia = c("Washingtonia", "Washington Palm"),
  Trachycarpus = c("Trachycarpus", "Windmill Palm"),
  Rhapis = c("Rhapis", "Lady Palm"),
  Bismarckia = c("Bismarckia", "Bismarck Palm"),
  Livistona = c("Livistona", "Chinese Fan Palm"),
  Cocos = c("Cocos", "Coconut Palm"),
  Dypsis = c("Dypsis", "Areca Palm"),
  Syagrus = c("Syagrus", "Queen Palm"),
  Sabal = c("Sabal", "Palmetto"),
  Caryota = c("Caryota", "Fishtail Palm"),
  Zamia = c("Zamia", "Cardboard Palm"),
  Encephalartos = c("Encephalartos", "Bread Palm"),
  Ceratozamia = c("Ceratozamia", "Horned Palm"),
  Macrozamia = c("Macrozamia", "Burrawang Palm"),
  Microcycas = c("Microcycas", "Cuban Cycad")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "house", subdept = "tropical", .before = 1)

epiphytes <- list(
  Tillandsia = c("Tillandsia", "Air Plant"),
  Platycerium = c("Platycerium", "Staghorn Fern"),
  Asplenium = c("Asplenium", "Bird's Nest Fern"),
  Orchids = c("Orchids", "Orchid"),
  Hoya = c("Hoya", "Wax Plant"),
  Rhipsalis = c("Rhipsalis", "Mistletoe Cactus"),
  Vriesea = c("Vriesea", "Flaming Sword"),
  Dischidia = c("Dischidia", "Ant Plant"),
  Guzmania = c("Guzmania", "Guzmania"),
  Aechmea = c("Aechmea", "Urn Plant"),
  Cryptanthus = c("Cryptanthus", "Earth Star"),
  Catopsis = c("Catopsis", "Bladderwort"),
  Billbergia = c("Billbergia", "Queen's Tears"),
  Cattleya = c("Cattleya", "Corsage Orchid"),
  Coelogyne = c("Coelogyne", "Necklace Orchid"),
  Masdevallia = c("Masdevallia", "Masdevallia Orchid")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "house", subdept = "epiphytes", .before = 1)

carnivorous <- list(
  Dionaea = c("Dionaea", "Venus Flytrap"),
  Sarracenia = c("Sarracenia", "Pitcher Plant"),
  Nepenthes = c("Nepenthes", "Tropical Pitcher Plant"),
  Drosera = c("Drosera", "Sundew"),
  Utricularia = c("Utricularia", "Bladderwort"),
  Pinguicula = c("Pinguicula", "Butterwort"),
  Cephalotus = c("Cephalotus", "Australian Pitcher Plant"),
  Darlingtonia = c("Darlingtonia", "Cobra Lily"),
  Heliamphora = c("Heliamphora", "Sun Pitcher"),
  Byblis = c("Byblis", "Rainbow Plant"),
  Genlisea = c("Genlisea", "Corkscrew Plant"),
  Aldrovanda = c("Aldrovanda", "Waterwheel Plant"),
  Brocchinia = c("Brocchinia"),
  Roridula = c("Roridula"),
  Drosophyllum = c("Drosophyllum", "Dewy Pine")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "house", subdept = "carnivorous", .before = 1)

ferns <- list(
  Pteris = c("Pteris", "Brake Fern"),
  Nephrolepis = c("Nephrolepis", "Boston Fern"),
  Asplenium = c("Asplenium", "Bird('?s)? Nest Fern"),
  Polystichum = c("Polystichum", "Sword Fern"),
  Adiantum = c("Adiantum", "Maidenhair Fern"),
  Cyrtomium = c("Cyrtomium", "Holly Fern"),
  Athyrium = c("Athyrium", "Lady Fern"),
  Dryopteris = c("Dryopteris", "Wood Fern"),
  Platycerium = c("Platycerium", "Staghorn Fern"),
  Blechnum = c("Blechnum", "Deer Fern"),
  Dicksonia = c("Dicksonia", "Tree Fern"),
  Osmunda = c("Osmunda", "Cinnamon Fern"),
  Matteuccia = c("Matteuccia", "Ostrich Fern"),
  Woodwardia = c("Woodwardia", "Chain Fern"),
  Davallia = c("Davallia", "Rabbit's Foot Fern"),
  Microsorum = c("Microsorum", "Kangaroo Fern"),
  Cibotium = c("Cibotium", "Hawaiian Tree Fern"),
  Lygodium = c("Lygodium", "Climbing Fern"),
  Marsilea = c("Marsilea", "Water Clover"),
  Thelypteris = c("Thelypteris", "maiden fern")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "house", subdept = "fern", .before = 1)

seasonal <- list(
  Euphorbia = c("Euphorbia", "Poinsettia"),
  Chrysanthemum = c("Chrysanthemum", "Mum"),
  Cyclamen = c("Cyclamen"),
  Primula = c("Primula", "Primrose"),
  Hippeastrum = c("Hippeastrum", "Amaryllis"),
  Lilium = c("Lilium", "Easter Lily"),
  Ilex = c("Ilex", "Holly"),
  Gaultheria = c("Gaultheria", "Wintergreen"),
  Erica = c("Erica", "Heather"),
  Hyacinthus = c("Hyacinthus", "Hyacinth"),
  Narcissus = c("Narcissus", "Daffodil"),
  Tulipa = c("Tulipa", "Tulip"),
  Euphorbia_milii = c("Euphorbia_milii", "Crown of Thorns"),
  Ardisia = c("Ardisia", "Coral Berry"),
  Camellia = c("Camellia"),
  Poinciana = c("Poinciana", "Royal Poinciana"),
  Alstroemeria = c("Alstroemeria", "Peruvian Lily"),
  Cineraria = c("Pericallis", "Florist's Cineraria")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "annuals", subdept = "seasonal", .before = 1)

other <- list(
  pot = c("pot", "coex", "Pressure Formed", "Co-Ex", "Pres Form", "CONTAINERS PW", "CONTAINERS"),
  media = c("media", "60Cft"),
  fertilizer = c("fertilizer", "Fertilizer-[:alpha:]*"),
  tag = c("tag", "[:alpha:]*-Tag"),
  fee = c("fee", "freight", "charge"),
  lighting = c("Lighting"),
  other = c("POP MATERIAL")
) |> enframe() |>
  unnest(value) |>
  dplyr::rename("genus" = name, "common name" = value) |>
  mutate(dept = "other", subdept = "other", .before = 1)

# Combine all into one list
plant_classifications <- herbs |> 
  add_row(vegetables) |> 
  add_row(fruits) |> 
  add_row(annuals) |>
  add_row(perennials) |>
  add_row(succulents) |>
  add_row(foliage) |>
  add_row(bulbs_tubers) |>
  add_row(ornamental_grasses) |>
  add_row(aquatic_plants) |>
  add_row(trees_shrubs) |>
  add_row(climbers_vines) |>
  add_row(orchids) |>
  add_row(groundcovers) |>
  add_row(bamboo) |>
  add_row(palms_cycads) |>
  add_row(epiphytes) |>
  add_row(carnivorous) |>
  add_row(ferns) |>
  add_row(seasonal) |>
  add_row(other) |>
  distinct() |>
  mutate(across(where(is.character),str_squish)) |>
  arrange(desc(str_length(`common name`)),str_rank(`common name`))
  

```


```{r filter, eval=TRUE}

## TODO

if(!exists("dCluster")) {
  dCluster <- new_cluster(n_cores-1)
  cluster_library_quiety <- purrr::quietly(cluster_library)
  cluster_library_quiety(dCluster, librarian::check_attached())
}



plants_classified <- plants_joined |>
  # partition(dCluster) |>
  dplyr::mutate(Department = if_else(Description |> str_to_lower() |> str_detect("(^|[:space:])(he)|(vf)|(herb)[:space:]"), "edibles",NA),
                Description = Description |> str_remove_all("(?<=([:space:]|^))(([Hh][Ee][Rr][Bb])|([Hh][Ee])|([Vv][Ff]))(?=([:space:]|$))") |> str_squish()) |>
  fuzzy_left_join(plant_classifications, by = c("Description" = "common name"), \(x,y) {
    str_detect(str_to_lower(x),str_c("(^|[:space:])",str_to_lower(y),"(((es)|s)?($|[:space:]))"))
    }) #|>
  # collect()
## TO VIEW WHAT ISN'T CAPTURED IN ASSIGNMENTS
plants_classified |>
  filter(dept |> is.na()) |>
  view()

plants_filtered <- plants_classified |>
  partition(dCluster) |>
  dplyr::filter((`Ship Date` >= "20240101" |> ymd())&(`Ship Date` < "20250101" |> ymd()),
                (str_detect(dept,"edible"))) |> # |str_detect(Department,"edible")))|>
                # Supplier |> str_equal("Kube Pak"),
                # (Description |> str_detect("(^|[:space:])(HE)|(VF)[:space:]"))|(`Customer PO #` |> str_to_lower() |> str_detect("(herb)|(veg)"))) |>
  # dplyr::mutate(Description = Description |> str_remove_all("(?<=([:space:]|^))((herb)|(he)|(vf))(?=([:space:]|$))") |> str_squish()) |>
  collect()



tags_filtered <- mtag_orders |>
  dplyr::filter((`Estimated Ship Date` >= "20230701" |> ymd())&(`Estimated Ship Date` < "20240101" |> ymd()),
                str_detect(`PO #` |> str_to_lower(),"(herb)|(veg)|(daniel)"))

```

```{r mtag_join, eval = TRUE}


plants_prep <- plants_filtered |>
  summarise(`QTY Ordered` = sum(`QTY Ordered`), .by = any_of(c("Description"))) |>
  rename_with(\(x) paste0("plants_",x))

tags_prep <- tags_filtered |>
  summarise(`Ordered Quantity` = sum(`Ordered Quantity`), .by = any_of(c("MT Item Description"))) |>
  rename_with(\(x) paste0("tags_",x))

aligned <- fuzzyjoin::fuzzy_full_join(plants_prep, tags_prep, by=c("plants_Description"="tags_MT Item Description"), match_fun = name_match)
## adding tag counts
aligned %<>%
  mutate(subdept = case_when(plants_Description |> str_to_lower() |> str_detect("(?<=(^|[:space:]))(he(rb)?)(?=($|[:space:]))") ~ "herb",
                             plants_Description |> str_to_lower() |> str_detect("(?<=(^|[:space:]))(vf)(?=($|[:space:]))") ~ "veg",
                             plants_Description |> str_to_lower() |> str_detect("(?<=(^|[:space:]))(lavandula)|(lavender)(?=($|[:space:]))") ~ "herb",
                             plants_Description |> str_to_lower() |> str_detect("(?<=(^|[:space:]))(eucalyptus)|(lemon[:space:]?bush)(?=($|[:space:]))") ~ "herb",
                             plants_Description |> str_to_lower() |> str_detect("(?<=(^|[:space:]))(marigold)(?=($|[:space:]))") ~ "veg",
                             plants_Description |> str_to_lower() |> str_detect("(?<=(^|[:space:]))(melampodium)(?=($|[:space:]))") ~ "veg",
                             .default = NA),
         tags_per_plug = case_match(subdept,
                                    c("herb") ~ 1,
                                    c("veg") ~ 4,
                                    .default = 1),
         tags_need = `plants_QTY Ordered` / tags_per_plug,
         tags_deficit = (tags_need - datawizard::convert_na_to(`tags_Ordered Quantity`,replacement = 0)) |> pmax(0))

# can i use dplyr::join with dplyr::closest() with pairwiseAligment scores? or maybe need to use fuzzyjoin


```


```{r export, eval=TRUE}
plants_joined %<>%
  mutate(size = case_when(str_detect(`Customer PO #`,"(^4.5)|(4.5[:space:]?((IN)|(in)|(\")))") ~ "4.5 in",
                           str_detect(`Customer PO #`,"^804") ~ "804",
                           str_detect(`Customer PO #`,"(^10)|(10[:space:]?((IN)|(in)|(\"))).*((HB)|(BSKT)|(BASKET))")  ~ "10 in hb",
                           str_detect(`Customer PO #`,"(^8)|(8[:space:]?((IN)|(in)|(\"))).*((HB)|(BSKT)|(BASKET))")  ~ "8 in hb",
                           str_detect(`Customer PO #`,"(^12)|(12[:space:]?((IN)|(in)|(\"))).*((HB)|(BSKT)|(BASKET))")  ~ "12 in hb",
                           str_detect(`Customer PO #`,"(^11)|(11[:space:]?((IN)|(in)|(\"))).*((HB)|(BSKT)|(BASKET))")  ~ "11 in hb",
                           str_detect(`Customer PO #`,"(^14)|(14[:space:]?((IN)|(in)|(\")))")  ~ "14 in",
                           str_detect(`Customer PO #`,"(^4)|(4[:space:]?((IN)|(in)|(\")))")  ~ "4 in",
                           str_detect(`Customer PO #`,"(^6)|(6[:space:]?((IN)|(in)|(\")))")  ~ "6 in",
                           str_detect(`Customer PO #`,"(^12)|(12[:space:]?((IN)|(in)|(\")))")  ~ "12 in",
                           str_detect(`Customer PO #`,"(^11)|(11[:space:]?((IN)|(in)|(\")))")  ~ "11 in",
                           str_detect(`Customer PO #`,"(^10)|(10[:space:]?((IN)|(in)|(\")))")  ~ "10 in",
                           str_detect(`Customer PO #`,"1[:space:]?((GAL)|(G[:space:])|(G$))")  ~ "1 gal",
                           str_detect(`Customer PO #`,"((HB)|(BSKT)|(BASKET))")  ~ "10 in hb",
                           str_detect(`Customer PO #`,"^(liner)|(LINER)")  ~ "liner",
                           str_detect(`Customer PO #`,"^PW")  ~ "PW",
                           .default = "other"))


write_xlsx(plants_joined, path = plants_dir |> fs::path("2024", "ball express fall 2024", "fall2024_ball&express_v0.1.xlsx"))
```

```{r averages, eval=FALSE}

plugs_tbl <- tibble_row(size = "4 in", plugs = 1) |> # .25
  tibble::add_case(size = "4.5 in", plugs = 1)|> # .07
  tibble::add_case(size = "6 in", plugs = 3)|> # .124
  tibble::add_case(size = "10 in hb", plugs = 5)|> # .079
  tibble::add_case(size = "11 in hb", plugs = 6)|> # .069
  tibble::add_case(size = "8 in hb", plugs = 4)|> # .09
  tibble::add_case(size = "14 in", plugs = 3)|>
  tibble::add_case(size = "1 gal", plugs = 1)|>
  tibble::add_case(size = "liner", plugs = 1)|>
  tibble::add_case(size = "PW", plugs = 1)|>
  tibble::add_case(size = "12 in hb", plugs = 7)|>
  tibble::add_case(size = "12 in", plugs = 7)|>
  tibble::add_case(size = "10 in", plugs = 5)|>
  tibble::add_case(size = "804", plugs = 1)

averages <- plants_joined |>
  dplyr::filter(`Ship Date` >= ymd("2024-01-01")) |>
  dplyr::mutate(category = if_else(str_detect(Supplier |> str_to_lower(), "four[:space:]?star"), "PW", "") |> str_c(size, sep = " ")) |>
  dplyr::summarise(dplyr::across(c("QTY Ordered","Total"),sum), .by = dplyr::any_of(c("category", "size"))) |>
  dplyr::left_join(plugs_tbl) |>
  dplyr::mutate(plug_avg_cost = Total / `QTY Ordered`,
                pot_avg_cost = plug_avg_cost * plugs) |>
  dplyr::filter(!is.na(pot_avg_cost)) |>
  select(1,3,4,6,7) |>
  dplyr::arrange(category,desc(`QTY Ordered`))

```


```{r terminateClusters, eval=FALSE}
# dplyr cluster
if(exists("dCluster")) rm(dCluster)

# doParallel cluster
if(!is_null(getDefaultCluster())) stopCluster(getDefaultCluster())
```