---
title: "pH and EC statistics"
date: 5 November 2024
output: html_notebook
---



```{r setup, echo=FALSE, error=TRUE, message=TRUE, warning=TRUE, include=FALSE}
# this block loads required packages and some custom functions. 
cran_pacs <- c("tidyverse","writexl","fs","stringr","rlang","magrittr","stats","foreach", "doParallel", "parallel", "fs", "janitor", "stringr","lubridate","forcats", "purrr","multidplyr", "readxl") 
dev_pacs <- c() 
bioc_pacs <- c()
py_pacs <- c()

# install installers
if(length(find.package("pak", quiet = TRUE))==0) install.packages("pak")
if(length(find.package("librarian", quiet = TRUE))==0) pak::pak("librarian")
installer_pacs <- Filter(librarian::check_installed, c(if (length(bioc_pacs) > 0) "BiocManager", if (length(py_pacs) > 0) "reticulate"))
if (length(installer_pacs) > 0) pak::pak(installer_pacs, upgrade = TRUE)

# install and load R pacs
r_pacs <- c(cran_pacs,dev_pacs,bioc_pacs) |> unique()
if (length(r_pacs) > 0) {
  pak::pak(r_pacs, upgrade = FALSE, ask = FALSE)
  librarian::shelf(r_pacs)
}

# install python packs
if (length(py_pacs)>0) {
  if (!reticulate::py_available(initialize = TRUE)) reticulate::install_python()
  if (reticulate::py_available(initialize = TRUE)) reticulate::py_install(py_pacs)
}

## register cores for foreach/doParallel
n_cores <- case_match(.Platform$OS.type,
                      "windows" ~ (parallel::detectCores() * 3/4) |> floor() |> max(1),
                      .default = (parallel::detectCores() - 1) |> max(1))
# registerDoParallel(cores=n_cores)
# stopImplicitCluster()

# doParallel cluster
if(!is_null(getDefaultCluster())) stopCluster(getDefaultCluster())
makeCluster(n_cores) |> setDefaultCluster()
registerDoParallel(getDefaultCluster())

# dplyr cluster
if(exists("dCluster")) rm(dCluster)
dCluster <- new_cluster(n_cores)
cluster_library_quiety <- purrr::quietly(cluster_library)
# cluster_library_quiety(dCluster, loadedNamespaces())
cluster_library_quiety(dCluster, librarian::check_attached())
```


```{r getData}

datapath <- "Greenstreet Growers/TeamSite - Documents/Shared/Production Greenstreet/Production Planning QC/Test Samples/Fall 2024 PM4 pansy/Medin Soil tests/ph tests fall 2024.xlsx" |> fs::path_home()

data <- datapath |> 
  read_xlsx() |>
  mutate(across(where(is.character), as_factor))

```

```{r plot}

# Pansy pH and EC

data |>
  mutate(date = date |> as.factor()) |> 
  filter(crop |> str_equal("pansy"),
         soil |> str_equal("PM4")) |>
  ggplot(aes(x = date, y = pH, color = `inside/outside`)) +
    geom_boxplot() +
    geom_jitter(width = 0.05, height = 0.05) +
    # facet_wrap(vars(soil)) +
    theme_minimal()

data |> 
  filter(crop |> str_equal("pansy"),
         soil |> str_equal("PM4")) |>
  ggplot(aes(x = date, y = EC, color = `inside/outside`)) +
    geom_smooth() +
    geom_jitter(width = 0.05, height = 0.05) +
    # facet_wrap(vars(soil)) +
    theme_minimal()

data |>
  # mutate(date = date |> as.factor()) |> 
  filter(crop |> str_equal("pansy")) |>
  ggplot(aes(x = date, y = pH, color = soil)) +
    # geom_boxplot() +
    geom_smooth() +
    geom_jitter(width = 0.05, height = 0.025) +
    theme_minimal()

data |>
  # mutate(date = date |> as.factor()) |> 
  filter(crop |> str_equal("pansy"),
         `inside/outside` |> str_equal("inside")) |>
  ggplot(aes(x = date, y = EC, color = soil)) +
    # geom_boxplot() +
    geom_smooth() +
    geom_jitter(width = 0.05, height = 0.025) +
    theme_minimal()

# Poinsettia pH
data |>
  mutate(date = date |> as.factor()) |> 
  filter(crop |> str_equal("poinsettia"),
         soil |> str_equal("promix")) |>
  ggplot(aes(x = date, y = pH, color = `inside/outside`)) +
    geom_boxplot() +
    geom_jitter(width = 0.05, height = 0.05) +
    # facet_wrap(vars(soil)) +
    theme_minimal()

```

