---
title: QVC AvantFlora Sales Analysis 2024 Season
author: Daniel R. Williams ^[Director of Quality Control, Greenstreet Growers, Lothian,
  MD] ^[PhD Candidate, Dept. of Ag. & Crop Science, Ohio State University, Columbus,  Ohio]
date: 18 March 2024
output:
  html_notebook: default
---

# Todo



```{r setup, echo=FALSE, error=TRUE, message=TRUE, warning=TRUE, include=FALSE}
# this block loads required packages and some custom functions. 

cran_pacs <- c("rlang", "pkgbuild","rmarkdown", "tidyselect", "tidyverse", "magrittr", "stats", "measurements", "knitr", "foreach", "doParallel", "parallel", "fs", "janitor", "stringr", "readxl", "writexl","fuzzyjoin", "chromote", "pdftools") 
dev_pacs <- c() ## "aperium/rutil")
bioc_pacs <- c() # "Biostrings"
py_pacs <- c() #"camelot-py"

# global option to stop prompting for installing from source.
options(install.packages.check.source = "no")

## function to quietly find list of packages
find_package_quiet <- function(pkgs, ...) unlist(find.package(pkgs, quiet = TRUE, ...))
install_as_needed <- function(pacs, inst_fun = install.packages, check_fun = find_package_quiet, ...) {
  inst_fun(setdiff(pacs,names(unlist(sapply(pacs,\(x) check_fun(x))))),...)
}

# install cran packs
if (length(cran_pacs) > 0) install_as_needed(cran_pacs,install.packages, quiet = TRUE)

# install github dev packs
if (length(dev_pacs)>0) {
  if (!requireNamespace("pak", quietly = TRUE)[]) install.packages("pak", quiet = TRUE)
  install_as_needed(dev_pacs,pak::pak, ask = FALSE, upgrade = TRUE)
}

# install bioc packs
if (length(bioc_pacs)>0) {
  if (!requireNamespace("BiocManager", quietly = TRUE)[]) install.packages("BiocManager", quiet = TRUE)
  # install_as_needed(c("DBI","xfun"))
  BiocManager::install(version = "3.18", update = FALSE, ask=FALSE)
  install_as_needed(bioc_pacs,BiocManager::install, update = FALSE, ask=FALSE)
}

if (!requireNamespace("librarian", quietly = TRUE)[]) install.packages("librarian", quiet = TRUE)
if (!requireNamespace("pak", quietly = TRUE)[]) install.packages("pak", quiet = TRUE)
librarian::shelf(cran_pacs, bioc_pacs, dev_pacs, quiet = TRUE)
installed_req_pkgs <- pak::pkg_status(c(cran_pacs, bioc_pacs, dev_pacs))$package
loaded_pacs <- search() |> stringr::str_extract("(?<=:).*$") |> na.omit()


# install python packs
if (length(py_pacs)>0) {
  if (!requireNamespace("reticulate", quietly = TRUE)[]) install.packages("reticulate", quiet = TRUE)
  if (!reticulate::py_available(initialize = TRUE)) reticulate::install_python()
  if (reticulate::py_available(initialize = TRUE)) reticulate::py_install(py_pacs)
}


if((("readxl" %in% installed_req_pkgs)&is_empty(find_package_quiet("readxl")))|(("writexl" %in% installed_req_pkgs)&is_empty(find_package_quiet("writexl")))) librarian::shelf("ycphs/openxlsx") #load openxlsx if read-/write-xl not avail
if(((("readxl" %in% installed_req_pkgs)&is_empty(find_package_quiet("readxl")))|(("writexl" %in% installed_req_pkgs)&is_empty(find_package_quiet("writexl"))))&(is_empty(find_package_quiet("openxlsx")))) librarian::shelf("colearendt/xlsx") # load xlsx if openxlsx not avail

## register cores for foreach
n_cores <- parallel::detectCores()
# registerDoParallel(cores=n_cores)
# stopImplicitCluster()


```

```{r xlxs_function, echo=FALSE, error=TRUE, message=TRUE, warning=TRUE, include=FALSE}
# These are some sloppy workarounds for reading and writing data from and to excel files. Some of the readxl and writexl are preferred but they are not universally supported. If they are not installed, these functions use on of the other two packages for xlsx-file handling in the order of preference (openxlsx is preferred over xlsx). For simplicity and robustness many features of the packages are not accessible except where they can be translated 1-to-1 across all three. Ideally, The resulting data should be approximately identical in structure, datatypes, and column names regardless of the function it is using to read or write data.

read_xlsx_flex <- function(path, sheet = NULL, range = NULL, col_names = TRUE) {
  if(nzchar(find.package("readxl"))) use_which <- "readxl"
  else if (nzchar(find.package("openxlsx"))) use_which <- "openxlsx"
  else if (nzchar(find.package("xlsx"))) use_which <- "xlsx"
  else return("please install one of: readxl, openxlsx, xlsx")
  #
  sheet_index <- switch (typeof(sheet),
    "NULL" = 1,
    "double" = sheet,
    "integer" = sheet,
    "numeric" = sheet,
    "character" = NULL
  )
  sheet_name <- switch (typeof(sheet),
    "NULL" = NULL,
    "double" = NULL,
    "integer" = NULL,
    "numeric" = NULL,
    "character" = sheet
  )
  # use_which <- "readxl"
  switch (use_which,
    "readxl" = readxl::read_xlsx(path = path, sheet = sheet, range = range, col_names = col_names),
    "openxlsx" = openxlsx::read.xlsx(xlsxFile = path, sheet = ifelse(!is_null(sheet_index), sheet_index, 1) , colNames = col_names, check.names = FALSE, sep.names = " "),
    "xlsx" = xlsx::read.xlsx(file = path, sheetIndex = sheet_index, sheetName = sheet_name, header = col_names, as.data.frame=TRUE, check.names = FALSE)
  )
}


write_xlsx_flex <- function(x, path = tempfile(fileext = ".xlsx")) {
  if(nzchar(find.package("writexl"))) use_which <- "writexl"
  else if (nzchar(find.package("openxlsx"))) use_which <- "openxlsx"
  else if (nzchar(find.package("xlsx"))) use_which <- "xlsx"
  else return("please install one of: writexl, openxlsx, xlsx")
  # use_which <- "xlsx"
  switch (use_which,
    "writexl" = writexl::write_xlsx(x = x, path = path, col_names = TRUE),
    "openxlsx" = openxlsx::write.xlsx(x = x, file = path, asTable = TRUE, overwrite = TRUE),
    "xlsx" = xlsx::write.xlsx2(x = as.data.frame(x), file = path, row.names = FALSE, showNA = FALSE) # puts the rownames in column A. removing them throws bugs.
  )
}

```

```{r getinput, echo=TRUE, error=TRUE, message=FALSE, warning=TRUE}

# over-ride using current iso_week / year by using number as a character vector eg: "11"
ship_week <- today() |> isoweek() |> as.character()
ship_year <- today() |> year() |> as.character()



dir_path <- "Greenstreet Growers/TeamSite - Documents/Shared/Production Greenstreet/Production Finished/QVC Spring 2024 Drop Ship/Sales Reports" |> path_home()

inventory_on_hand_path <- dir_path |> path("GM36_sku_inventory_2024-03-18.csv")
sales_by_daterange_path <- dir_path |> path("GM36_sku_sales_2024-03-14_through_2024-03-18.csv")

```

```{r datasetup, echo=TRUE, error=TRUE, message=FALSE, warning=TRUE}
inventory_on_hand <- inventory_on_hand_path |> read_csv()

sales_by_daterange <- sales_by_daterange_path |> read_csv()

#joining 
inventry_and_sales <- left_join(sales_by_daterange, inventory_on_hand) |>
  janitor::remove_empty() |>
  janitor::remove_constant() |>
  dplyr::relocate(matches("^SKN_"),matches("_QUANTITY$"),matches("_AMOUNT$"))
```

```{r export}

inventry_and_sales |>
  write_xlsx_flex(dir_path |> path(paste(sep = "_","QVC_AF_inventory_and_sales",today(),".xlsx")))

```
